namespace MultiThreads
{
    [default_interface]
    runtimeclass MyContentPage : Windows.UI.Xaml.Controls.Page
    {
        MyContentPage ( );
        Int32 MyProperty;
        Double NavViewCompactModeThresholdWidth{ get; };
    }
}
