// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200917.4

void* winrt_make_MultiThreads_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::MultiThreads::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::MultiThreads
{
    MainPage::MainPage() :
        MainPage(make<MultiThreads::implementation::MainPage>())
    {
    }
}
