//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::MultiThreads::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainPageT : public ::winrt::MultiThreads::implementation::MainPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename MainPageT::base_type;
        using base_type::base_type;
        using class_type = typename MainPageT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView NavView()
        {
            return _NavView;
        }
        void NavView(::winrt::Microsoft::UI::Xaml::Controls::NavigationView value)
        {
            _NavView = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItemHeader MainPagesHeader()
        {
            return _MainPagesHeader;
        }
        void MainPagesHeader(::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItemHeader value)
        {
            _MainPagesHeader = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox NavViewSearchBox()
        {
            return _NavViewSearchBox;
        }
        void NavViewSearchBox(::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox value)
        {
            _NavViewSearchBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Frame ContentFrame()
        {
            return _ContentFrame;
        }
        void ContentFrame(::winrt::Windows::UI::Xaml::Controls::Frame value)
        {
            _ContentFrame = value;
        }
        
         ::winrt::com_ptr<::winrt::MultiThreads::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct MainPage_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::NavigationView _NavView{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::NavigationViewItemHeader _MainPagesHeader{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AutoSuggestBox _NavViewSearchBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Frame _ContentFrame{nullptr};
    };
}

