// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200917.4

void* winrt_make_MultiThreads_MyContentPage()
{
    return winrt::detach_abi(winrt::make<winrt::MultiThreads::implementation::MyContentPage>());
}
WINRT_EXPORT namespace winrt::MultiThreads
{
    MyContentPage::MyContentPage() :
        MyContentPage(make<MultiThreads::implementation::MyContentPage>())
    {
    }
}
