// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200917.4

#ifndef WINRT_Microsoft_UI_Xaml_Controls_Primitives_1_H
#define WINRT_Microsoft_UI_Xaml_Controls_Primitives_1_H
#include "winrt/impl/Microsoft.UI.Xaml.Controls.Primitives.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Controls::Primitives
{
    struct __declspec(empty_bases) IAutoSuggestBoxHelper :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutoSuggestBoxHelper>
    {
        IAutoSuggestBoxHelper(std::nullptr_t = nullptr) noexcept {}
        IAutoSuggestBoxHelper(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAutoSuggestBoxHelperStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAutoSuggestBoxHelperStatics>
    {
        IAutoSuggestBoxHelperStatics(std::nullptr_t = nullptr) noexcept {}
        IAutoSuggestBoxHelperStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorPickerSlider :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorPickerSlider>
    {
        IColorPickerSlider(std::nullptr_t = nullptr) noexcept {}
        IColorPickerSlider(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorPickerSliderFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorPickerSliderFactory>
    {
        IColorPickerSliderFactory(std::nullptr_t = nullptr) noexcept {}
        IColorPickerSliderFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorPickerSliderStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorPickerSliderStatics>
    {
        IColorPickerSliderStatics(std::nullptr_t = nullptr) noexcept {}
        IColorPickerSliderStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorSpectrum :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorSpectrum>
    {
        IColorSpectrum(std::nullptr_t = nullptr) noexcept {}
        IColorSpectrum(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorSpectrumFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorSpectrumFactory>
    {
        IColorSpectrumFactory(std::nullptr_t = nullptr) noexcept {}
        IColorSpectrumFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColorSpectrumStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColorSpectrumStatics>
    {
        IColorSpectrumStatics(std::nullptr_t = nullptr) noexcept {}
        IColorSpectrumStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColumnMajorUniformToLargestGridLayout :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColumnMajorUniformToLargestGridLayout>
    {
        IColumnMajorUniformToLargestGridLayout(std::nullptr_t = nullptr) noexcept {}
        IColumnMajorUniformToLargestGridLayout(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColumnMajorUniformToLargestGridLayoutFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColumnMajorUniformToLargestGridLayoutFactory>
    {
        IColumnMajorUniformToLargestGridLayoutFactory(std::nullptr_t = nullptr) noexcept {}
        IColumnMajorUniformToLargestGridLayoutFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IColumnMajorUniformToLargestGridLayoutStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IColumnMajorUniformToLargestGridLayoutStatics>
    {
        IColumnMajorUniformToLargestGridLayoutStatics(std::nullptr_t = nullptr) noexcept {}
        IColumnMajorUniformToLargestGridLayoutStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IComboBoxHelper :
        Windows::Foundation::IInspectable,
        impl::consume_t<IComboBoxHelper>
    {
        IComboBoxHelper(std::nullptr_t = nullptr) noexcept {}
        IComboBoxHelper(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IComboBoxHelperStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IComboBoxHelperStatics>
    {
        IComboBoxHelperStatics(std::nullptr_t = nullptr) noexcept {}
        IComboBoxHelperStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommandBarFlyoutCommandBar :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommandBarFlyoutCommandBar>
    {
        ICommandBarFlyoutCommandBar(std::nullptr_t = nullptr) noexcept {}
        ICommandBarFlyoutCommandBar(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommandBarFlyoutCommandBarFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommandBarFlyoutCommandBarFactory>
    {
        ICommandBarFlyoutCommandBarFactory(std::nullptr_t = nullptr) noexcept {}
        ICommandBarFlyoutCommandBarFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommandBarFlyoutCommandBarTemplateSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommandBarFlyoutCommandBarTemplateSettings>
    {
        ICommandBarFlyoutCommandBarTemplateSettings(std::nullptr_t = nullptr) noexcept {}
        ICommandBarFlyoutCommandBarTemplateSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusFilterConverter :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusFilterConverter>
    {
        ICornerRadiusFilterConverter(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusFilterConverter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusFilterConverterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusFilterConverterStatics>
    {
        ICornerRadiusFilterConverterStatics(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusFilterConverterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusToThicknessConverter :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusToThicknessConverter>
    {
        ICornerRadiusToThicknessConverter(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusToThicknessConverter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICornerRadiusToThicknessConverterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICornerRadiusToThicknessConverterStatics>
    {
        ICornerRadiusToThicknessConverterStatics(std::nullptr_t = nullptr) noexcept {}
        ICornerRadiusToThicknessConverterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) INavigationViewItemPresenter :
        Windows::Foundation::IInspectable,
        impl::consume_t<INavigationViewItemPresenter>
    {
        INavigationViewItemPresenter(std::nullptr_t = nullptr) noexcept {}
        INavigationViewItemPresenter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) INavigationViewItemPresenterFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<INavigationViewItemPresenterFactory>
    {
        INavigationViewItemPresenterFactory(std::nullptr_t = nullptr) noexcept {}
        INavigationViewItemPresenterFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) INavigationViewItemPresenterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<INavigationViewItemPresenterStatics>
    {
        INavigationViewItemPresenterStatics(std::nullptr_t = nullptr) noexcept {}
        INavigationViewItemPresenterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRepeatedScrollSnapPoint :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRepeatedScrollSnapPoint>
    {
        IRepeatedScrollSnapPoint(std::nullptr_t = nullptr) noexcept {}
        IRepeatedScrollSnapPoint(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRepeatedScrollSnapPointFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRepeatedScrollSnapPointFactory>
    {
        IRepeatedScrollSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
        IRepeatedScrollSnapPointFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRepeatedZoomSnapPoint :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRepeatedZoomSnapPoint>
    {
        IRepeatedZoomSnapPoint(std::nullptr_t = nullptr) noexcept {}
        IRepeatedZoomSnapPoint(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRepeatedZoomSnapPointFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IRepeatedZoomSnapPointFactory>
    {
        IRepeatedZoomSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
        IRepeatedZoomSnapPointFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollController :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollController>
    {
        IScrollController(std::nullptr_t = nullptr) noexcept {}
        IScrollController(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerAddScrollVelocityRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerAddScrollVelocityRequestedEventArgs>
    {
        IScrollControllerAddScrollVelocityRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerAddScrollVelocityRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerAddScrollVelocityRequestedEventArgsFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerAddScrollVelocityRequestedEventArgsFactory>
    {
        IScrollControllerAddScrollVelocityRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerAddScrollVelocityRequestedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerInteractionRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerInteractionRequestedEventArgs>
    {
        IScrollControllerInteractionRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerInteractionRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerInteractionRequestedEventArgsFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerInteractionRequestedEventArgsFactory>
    {
        IScrollControllerInteractionRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerInteractionRequestedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerScrollByRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerScrollByRequestedEventArgs>
    {
        IScrollControllerScrollByRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerScrollByRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerScrollByRequestedEventArgsFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerScrollByRequestedEventArgsFactory>
    {
        IScrollControllerScrollByRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerScrollByRequestedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerScrollToRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerScrollToRequestedEventArgs>
    {
        IScrollControllerScrollToRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerScrollToRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollControllerScrollToRequestedEventArgsFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollControllerScrollToRequestedEventArgsFactory>
    {
        IScrollControllerScrollToRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollControllerScrollToRequestedEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollPresenter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollPresenter>
    {
        IScrollPresenter(std::nullptr_t = nullptr) noexcept {}
        IScrollPresenter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollPresenterFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollPresenterFactory>
    {
        IScrollPresenterFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollPresenterFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollPresenterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollPresenterStatics>
    {
        IScrollPresenterStatics(std::nullptr_t = nullptr) noexcept {}
        IScrollPresenterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollSnapPoint :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollSnapPoint>
    {
        IScrollSnapPoint(std::nullptr_t = nullptr) noexcept {}
        IScrollSnapPoint(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollSnapPointBase :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollSnapPointBase>
    {
        IScrollSnapPointBase(std::nullptr_t = nullptr) noexcept {}
        IScrollSnapPointBase(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollSnapPointBaseFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollSnapPointBaseFactory>
    {
        IScrollSnapPointBaseFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollSnapPointBaseFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScrollSnapPointFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScrollSnapPointFactory>
    {
        IScrollSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
        IScrollSnapPointFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ISnapPointBase :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISnapPointBase>
    {
        ISnapPointBase(std::nullptr_t = nullptr) noexcept {}
        ISnapPointBase(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ISnapPointBaseFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISnapPointBaseFactory>
    {
        ISnapPointBaseFactory(std::nullptr_t = nullptr) noexcept {}
        ISnapPointBaseFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITabViewListView :
        Windows::Foundation::IInspectable,
        impl::consume_t<ITabViewListView>
    {
        ITabViewListView(std::nullptr_t = nullptr) noexcept {}
        ITabViewListView(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ITabViewListViewFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<ITabViewListViewFactory>
    {
        ITabViewListViewFactory(std::nullptr_t = nullptr) noexcept {}
        ITabViewListViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IZoomSnapPoint :
        Windows::Foundation::IInspectable,
        impl::consume_t<IZoomSnapPoint>
    {
        IZoomSnapPoint(std::nullptr_t = nullptr) noexcept {}
        IZoomSnapPoint(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IZoomSnapPointBase :
        Windows::Foundation::IInspectable,
        impl::consume_t<IZoomSnapPointBase>
    {
        IZoomSnapPointBase(std::nullptr_t = nullptr) noexcept {}
        IZoomSnapPointBase(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IZoomSnapPointBaseFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IZoomSnapPointBaseFactory>
    {
        IZoomSnapPointBaseFactory(std::nullptr_t = nullptr) noexcept {}
        IZoomSnapPointBaseFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IZoomSnapPointFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IZoomSnapPointFactory>
    {
        IZoomSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
        IZoomSnapPointFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
