// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200917.4

#ifndef WINRT_MultiThreads_1_H
#define WINRT_MultiThreads_1_H
#include "winrt/impl/MultiThreads.0.h"
WINRT_EXPORT namespace winrt::MultiThreads
{
    struct __declspec(empty_bases) IMainPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMyContentPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMyContentPage>
    {
        IMyContentPage(std::nullptr_t = nullptr) noexcept {}
        IMyContentPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
